-- ============================================================================
-- StockPlatform
-- Migration: 0020_reference_tables.sql
-- Description: Core reference tables
-- ============================================================================

-- ============================================================================
-- MARKETS
-- ============================================================================

CREATE TABLE core.markets
(
    market_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    country_code   CHAR(2),
    timezone       VARCHAR(64) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_markets_name UNIQUE (name)
);

-- ============================================================================
-- EXCHANGES
-- ============================================================================

CREATE TABLE core.exchanges
(
    exchange_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id      BIGINT NOT NULL,
    mic            VARCHAR(8) NOT NULL,
    code           VARCHAR(16) NOT NULL,
    name           TEXT NOT NULL,
    timezone       VARCHAR(64) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_exchanges_market
        FOREIGN KEY (market_id)
        REFERENCES core.markets (market_id),
    CONSTRAINT uq_exchanges_mic UNIQUE (mic),
    CONSTRAINT uq_exchanges_code UNIQUE (code)
);

-- ============================================================================
-- ASSET TYPES
-- ============================================================================

CREATE TABLE core.asset_types
(
    asset_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(32) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_asset_types_name UNIQUE (name)
);

-- ============================================================================
-- CURRENCIES
-- ============================================================================

CREATE TABLE core.currencies
(
    currency_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           CHAR(3) NOT NULL,
    name           TEXT NOT NULL,
    symbol         VARCHAR(8),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_currencies_code UNIQUE (code)
);

-- ============================================================================
-- ASSETS
-- ============================================================================

CREATE TABLE core.assets
(
    asset_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          VARCHAR(16) NOT NULL,
    provider_symbol VARCHAR(16),
    name            TEXT NOT NULL,
    display_name    TEXT,
    exchange_id     BIGINT NOT NULL,
    asset_type_id   BIGINT NOT NULL,
    currency_id     BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_assets_exchange
        FOREIGN KEY (exchange_id)
        REFERENCES core.exchanges (exchange_id),
    CONSTRAINT fk_assets_asset_type
        FOREIGN KEY (asset_type_id)
        REFERENCES core.asset_types (asset_type_id),
    CONSTRAINT fk_assets_currency
        FOREIGN KEY (currency_id)
        REFERENCES core.currencies (currency_id),
    CONSTRAINT uq_assets_exchange_ticker
        UNIQUE (exchange_id, ticker)
);

-- ============================================================================
-- UNIVERSES
-- ============================================================================

CREATE TABLE core.universes
(
    universe_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(32) NOT NULL,
    name           TEXT NOT NULL,
    sort_order     INTEGER NOT NULL DEFAULT 0,
    provider       VARCHAR(64) NOT NULL,
    enabled        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_universes_code
        UNIQUE (code)
);

-- ============================================================================
-- UNIVERSE MEMBERS
-- ============================================================================

CREATE TABLE core.universe_members
(
    universe_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universe_id        BIGINT NOT NULL,
    asset_id           BIGINT,
    ticker             VARCHAR(16) NOT NULL,
    company_name       TEXT NOT NULL,
    sector             TEXT,
    industry           TEXT,
    loaded_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_universe_members_universe
        FOREIGN KEY (universe_id)
        REFERENCES core.universes (universe_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_universe_members_asset
        FOREIGN KEY (asset_id)
        REFERENCES core.assets (asset_id),
    CONSTRAINT uq_universe_member
        UNIQUE (universe_id, ticker)
);

-- ============================================================================
-- DATA PROVIDERS
-- ============================================================================

CREATE TABLE core.data_providers
(
    provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20) NOT NULL,
    name        TEXT NOT NULL,
    website     TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_data_providers_code
        UNIQUE (code)
);

CREATE INDEX ix_universe_members_universe
    ON core.universe_members (universe_id);
CREATE INDEX ix_universe_members_asset
    ON core.universe_members (asset_id);
CREATE INDEX ix_universe_members_ticker
    ON core.universe_members (ticker);