-- ============================================================================
-- FUNDAMENTALS (CURRENT SNAPSHOT)
-- ============================================================================
CREATE TABLE market.fundamentals
(
    fundamental_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id       BIGINT NOT NULL,
    provider_id    BIGINT NOT NULL,
    metric_code    VARCHAR(50) NOT NULL,
    numeric_value  NUMERIC(30,10),
    text_value     TEXT,
    date_value     DATE,
    boolean_value  BOOLEAN,
    currency_id    BIGINT,
    as_of_date     DATE,
    loaded_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_fundamentals_metric_code
        CHECK (
            metric_code ~ '^[A-Z][A-Z0-9_]*$'
        ),
    CONSTRAINT fk_fundamentals_asset
        FOREIGN KEY (asset_id)
        REFERENCES core.assets (asset_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fundamentals_provider
        FOREIGN KEY (provider_id)
        REFERENCES core.data_providers (provider_id),
    CONSTRAINT fk_fundamentals_currency
        FOREIGN KEY (currency_id)
        REFERENCES core.currencies (currency_id),
    CONSTRAINT uq_fundamentals
        UNIQUE (
            asset_id,
            provider_id,
            metric_code
        )
);


-- ============================================================================
-- FUNDAMENTAL HISTORY
-- ============================================================================
CREATE TABLE market.fundamental_history
(
    history_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id       BIGINT NOT NULL,
    provider_id    BIGINT NOT NULL,
    metric_code    VARCHAR(50) NOT NULL,
    numeric_value  NUMERIC(30,10),
    text_value     TEXT,
    date_value     DATE,
    boolean_value  BOOLEAN,
    currency_id    BIGINT,
    as_of_date     DATE,
    loaded_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
     CONSTRAINT ck_fundamental_history_metric_code
        CHECK (
            metric_code ~ '^[A-Z][A-Z0-9_]*$'
        ),
    CONSTRAINT fk_fundamental_history_asset
        FOREIGN KEY (asset_id)
        REFERENCES core.assets (asset_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fundamental_history_provider
        FOREIGN KEY (provider_id)
        REFERENCES core.data_providers (provider_id),
    CONSTRAINT fk_fundamental_history_currency
        FOREIGN KEY (currency_id)
        REFERENCES core.currencies (currency_id)
);

